=== dibanescu/msTest-git/ProjectDMLwithGRO_11nov2016/Business Documents/clientinfo.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://unicredit.eu/xmlns/V1/anagrafe" xmlns:tns="http://unicredit.eu/xmlns/V1/anagrafe" >
	<xs:element name="GetClientByNDGRequest">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ndg" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetClientByNDGResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="client" type="tns:Client"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Client">
		<xs:sequence>
			<xs:element name="ndg" type="xs:string"/>
			<xs:element name="salutation" type="xs:string"/>
			<xs:element name="lang" type="xs:string"/>
			<xs:element name="firstName" type="xs:string"/>
			<xs:element name="lastName" type="xs:string"/>
			<xs:element name="birthDate" type="xs:date"/>
			<xs:element name="preferedCategories">
				<xs:complexType>
					<xs:sequence maxOccurs="unbounded" minOccurs="0">
						<xs:element name="category" type="xs:string"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== dibanescu/msTest-git/ProjectDMLwithGROA/Testdata/clientinfo_GetClientByNDGResponse_Input.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2015 rel. 4 (x64) (http://www.altova.com)-->
<GetClientByNDGResponse xmlns="http://unicredit.eu/xmlns/V1/anagrafe" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://unicredit.eu/xmlns/V1/anagrafe clientinfo.xsd">
	<client>
		<ndg>String</ndg>
		<salutation>String</salutation>
		<lang>String</lang>
		<firstName>String</firstName>
		<lastName>String</lastName>
		<birthDate>1957-08-13</birthDate>
		<preferedCategories>
			<category>String</category>
			<category>String</category>
		</preferedCategories>
	</client>
</GetClientByNDGResponse>
